language: node_js

branches:
  only:
    - master
    
node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"
  
before_script:
  - npm install -g grunt-cli

notifications:
  email:
    - spicydonuts@gmail.com
